<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE Patient [
    <!ELEMENT Patient (patientName, allergies, Doctors,visits )>
    <!ATTLIST Patient patientID CDATA #REQUIRED
                      dateofbirth CDATA #REQUIRED
                      bloodtype CDATA #REQUIRED
                      email CDATA #REQUIRED
                      username CDATA #REQUIRED>
                      
    <!ELEMENT patientName (#PCDATA)>
    <!ELEMENT allergies (Allergies+)>
    <!ELEMENT Doctors (Doctor+)> 
    <!ELEMENT visits (Visit+)>
    <!ELEMENT Allergies (allergiesName)>
    <!ATTLIST Allergies allergiesID CDATA #REQUIRED>
    <!ELEMENT allergiesName (#PCDATA)>   
    <!ELEMENT Doctor (name, surname,specialty )>
    <!ATTLIST Doctor contact CDATA #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT surname (#PCDATA)>
    <!ELEMENT specialty (#PCDATA)>
    <!ELEMENT Visit (#PCDATA)>
    <!ATTLIST Visit visit_id CDATA #REQUIRED
                    visit_date CDATA #REQUIRED
                    visit_observation CDATA #REQUIRED>

    
                    
]>                  
<Patient patientID="456" dateofbirth="1992-06-15" bloodtype="O+" email="james.bond@gmail.com" username="patient456">
    <patientName>John Doe</patientName>
    <allergies>
        <Allergies allergiesID="001">
			<allergiesName>Peanuts</allergiesName>
		</Allergies>
        <Allergies allergiesID="002">
			<allergiesName>Shellfish</allergiesName>
        </Allergies>
    </allergies>
    <Doctors>
        <Doctor contact="johndoe@gmail.com">
			<name>Jane</name>
            <surname>Smith</surname>
            <specialty>Dermatology</specialty>
        </Doctor>
        <Doctor contact="mark.johnson@gmail.com">
			 <name>Mark</name>
            <surname>Johnson</surname>
            <specialty>Pediatrics</specialty>
        </Doctor>
    </Doctors>
    <visits>
        <Visit visit_id="121" visit_date="01/01/2001" visit_observation="Nice health">
        </Visit>
        <Visit visit_id="122" visit_date="02/01/2001" visit_observation="Not so nice health">
        </Visit>
    </visits>
</Patient>
